// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ys0L8CMh9Wi95H8PT3zqV0q1A5sJ9vw',
    appId: '1:1003112621943:web:2c0b04b2c63ff53b076372',
    messagingSenderId: '1003112621943',
    projectId: 'coffeesort-e76b0',
    authDomain: 'coffeesort-e76b0.firebaseapp.com',
    storageBucket: 'coffeesort-e76b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4gMAktHNmByMLWGRTZ_4aLriUIS0ReY',
    appId: '1:1003112621943:android:0c776ef8b4a1ebd0076372',
    messagingSenderId: '1003112621943',
    projectId: 'coffeesort-e76b0',
    storageBucket: 'coffeesort-e76b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInFq46Fq0dQHwTz9-71GWbzPS_NZD_20',
    appId: '1:1003112621943:ios:ea188a8fbf6152b5076372',
    messagingSenderId: '1003112621943',
    projectId: 'coffeesort-e76b0',
    storageBucket: 'coffeesort-e76b0.firebasestorage.app',
    iosBundleId: 'com.example.coffeesort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInFq46Fq0dQHwTz9-71GWbzPS_NZD_20',
    appId: '1:1003112621943:ios:ea188a8fbf6152b5076372',
    messagingSenderId: '1003112621943',
    projectId: 'coffeesort-e76b0',
    storageBucket: 'coffeesort-e76b0.firebasestorage.app',
    iosBundleId: 'com.example.coffeesort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Ys0L8CMh9Wi95H8PT3zqV0q1A5sJ9vw',
    appId: '1:1003112621943:web:753f052d0a4b7128076372',
    messagingSenderId: '1003112621943',
    projectId: 'coffeesort-e76b0',
    authDomain: 'coffeesort-e76b0.firebaseapp.com',
    storageBucket: 'coffeesort-e76b0.firebasestorage.app',
  );
}
